blogenv/blog_project/blog_app/urls.py
from django.contrib import admin
from django.urls import path
from blog_app import views


app_name='blog_app'


urlpatterns = [

    path('',views.bloglist.as_view(),name='blog_list'),
    path('write_blog/',views.createblog.as_view(),name='createblog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('myblogs/', views.myblogs.as_view(), name='myblogs'),
    path('like/<pk>', views.liked, name='like'),
    path('dislike/<pk>', views.disliked, name='dislike'),
    path('editblog/<pk>', views.editblog.as_view(), name='editblog'),

]

blogenv/blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from blog_project import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogenv/blog_project/login_app/urls.py
from django.contrib import admin
from django.urls import path
from login_app import views


app_name='login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('password/', views.updatepass, name='updatepassword'),
    path('uploadpic/', views.uploadprofilepic, name='uploadpic'),
    path('changepic/', views.changeprofilepic, name='changepic'),

]

blogenv/blog_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<title>{% block title %}Blog{% endblock %}</title>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="nav-item ">
        <a class="nav-link" href="{% url 'index' %}">
            <h4><img src="/media/blog_pics/icon9.png" class="rounded-circle" height="60px" width="70px"></h4>
       </a>
      </li>

      {% if user.is_authenticated %}
        <li class="nav-item" style=" margin-left: 20px; margin-top:25px; color:#4ee460;"><h4>Welcome</h4></li>
        <div class="dropdown show" style="position:relative; margin-top:16px;">
            <a class=" nav-link dropdown-toggle" href="#"  data-toggle="dropdown" style="font-size: 22px;">{{user.username}}</a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="margin-top: 8px;">
            <a class="dropdown-item" href="{% url 'login_app:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'blog_app:createblog' %}">Write Blog</a>
            <a class="dropdown-item" href="{% url 'blog_app:myblogs' %}">My Blogs</a>
            <hr>
            <a class="dropdown-item" href="{% url 'login_app:logout' %}">Logout</a>
          </div>
        </div>
    {% else %}
      <li class="nav-item" style="margin-top:14px">
      <a class="nav-link" href="{% url 'login_app:signup' %}" style="color:#4ee460;"><h4>Signup</h4></a>
      </li>

      <li class="nav-item" style="margin-top:14px">
      <a class="nav-link" href="{% url 'login_app:login' %}" style="color:#4ee460;"><h4>Login</h4></a>
      </li>
    {% endif %}
      </ul>
  </div>
</nav>

<div class="container" style="padding-top:20px">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>