blogenv/blog_project/blog_app/urls.py
from django.contrib import admin
from django.urls import path
from blog_app import views


app_name='blog_app'


urlpatterns = [

    path('',views.bloglist.as_view(),name='blog_list'),
    path('write_blog/',views.createblog.as_view(),name='createblog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('myblogs/', views.myblogs.as_view(), name='myblogs'),
    path('like/<pk>', views.liked, name='like'),
    path('dislike/<pk>', views.disliked, name='dislike'),
    path('editblog/<pk>', views.editblog.as_view(), name='editblog'),

]

blogenv/blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from blog_project import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogenv/blog_project/login_app/urls.py
from django.contrib import admin
from django.urls import path
from login_app import views


app_name='login_app'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('password/', views.updatepass, name='updatepassword'),
    path('uploadpic/', views.uploadprofilepic, name='uploadpic'),
    path('changepic/', views.changeprofilepic, name='changepic'),

]

blogenv/blog_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class user_profile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

blogenv/blog_project/login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from login_app.models import *

class signupform(UserCreationForm):
    email=forms.EmailField(label="Email address", required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class updateprofile_form(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name','password']

class profilepic(forms.ModelForm):
    class Meta:
        model = user_profile
        fields= ['profile_pic']

blogenv/blog_project/login_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from login_app.forms import signupform, updateprofile_form, profilepic
# Create your views here.
def sign_up(request):
    diction={}
    registered=False
    form=signupform()
    if request.method=='POST':
        form=signupform(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True
    diction.update({'form':form})
    diction.update({'registered': registered})
    return render(request, 'login_app/signup.html', context=diction)


def user_login(request):
    diction={}
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user=authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    diction.update({'form':form})
    return render(request, 'login_app/login.html', context=diction)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    return render(request,'login_app/profile.html',context={})

@login_required
def updateprofile(request):
    updated=False
    diction={}
    current_user=request.user
    form=updateprofile_form(instance=current_user)
    if request.method=='POST':
        form=updateprofile_form(request.POST,instance=current_user)
        if form.is_valid():
            form.save()
            updated=True
    diction.update({'form':form, 'updated':updated})
    return render(request, 'login_app/changeprofile.html', context=diction)
@login_required
def updatepass(request):
    diction = {}
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method=='POST':
        form=PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:login'))
    diction.update({'form':form})
    return render(request, 'login_app/changePass.html', context=diction)

@login_required
def uploadprofilepic(request):
    diction={}
    form=profilepic()
    if request.method=='POST':
        form=profilepic(request.POST, request.FILES)
        if form.is_valid():
            user_obj=form.save(commit=False)
            user_obj.user=request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    diction.update({'form':form})
    return render(request, 'login_app/uploadpic.html', context=diction)
@login_required
def changeprofilepic(request):
    diction={}
    form=profilepic(instance=request.user.userprofile)
    if request.method=='POST':
        form=profilepic(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login_app:profile'))
    diction.update({'form': form})
    return render(request, 'login_app/uploadpic.html', context=diction)

blogenv/blog_project/templates/login_app/changepass.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Password{% endblock %}
{% block content %}

<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Save change</button>
</form>

{% endblock %}

blogenv/blog_project/templates/login_app/changeprofile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Profile{% endblock %}
{% block content %}
{% if updated %}
<div class="alert alert-success">Profile Updated Successfully.</div>
{% else %}
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm" >Save Changes</button>
</form>
{% endif %}
{% endblock %}

blogenv/blog_project/templates/login_app/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock %}
{% block content %}
    <form method="POST">
        <h3>Login</h3>
        {{form|crispy}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success btn-sm" value="Login">
    </form>
{% endblock %}

blogenv/blog_project/templates/login_app/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %} Profile {% endblock %}
{% block content %}
<h4>Profile</h4>
{% if user.userprofile %}
<img src="/media/{{user.userprofile.profile_pic}}" class="rounded-circle" width="100px"><br>
<a href="{% url 'login_app:changepic' %}" class="btn btn-warning btn-sm" style="margin-top: 10px; margin-bottom: 10px;">Change Pic</a>
{% else %}
<img src="/media/profile_pics/default_user.png" class="rounded-circle" width="100px"><br>
<a href="{% url 'login_app:uploadpic' %}" class="btn btn-info btn-sm" style="margin-top: 10px; margin-bottom: 10px;">Upload Pic</a>
{% endif %}
<h5>User name:&ensp;{{user.username}}</h5>
<h5>Email:&ensp;{{user.email}}</h5>
<h5>Name:&ensp;{{user.first_name}}{{user.last_name}}</h5>
<a class="btn btn-warning btn-sm" href="{% url 'login_app:updateprofile' %}">Update Profile</a>
{% endblock %}

blogenv/blog_project/templates/login_app/signup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Signup{% endblock %}
{% block content %}
    {% if registered %}
        <div class="alert alert-success">
            Account created successfully.<a href="{% url 'login_app:login' %}">Login</a>
        </div>
        {% else %}
        <h3>Create new account</h3>
        <form method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-success btn-sm" value="Create account">
        </form><br>
        <p>Alread have an account?<a href="{% url 'login_app:login' %}">Login</a></p>
    {% endif %}
{% endblock %}

blogenv/blog_project/templates/login_app/uploadpic.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Upload pic{% endblock %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-info btn-sm">Upload</button>
</form>

{% endblock %}