blogenv/blog_project/blog_app/urls.py
from django.contrib import admin
from django.urls import path
from blog_app import views


app_name='blog_app'


urlpatterns = [

    path('',views.bloglist.as_view(),name='blog_list'),
    path('write_blog/',views.createblog.as_view(),name='createblog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('myblogs/', views.myblogs.as_view(), name='myblogs'),
    path('like/<pk>', views.liked, name='like'),
    path('dislike/<pk>', views.disliked, name='dislike'),
    path('editblog/<pk>', views.editblog.as_view(), name='editblog'),

]

blogenv/blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from blog_project import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('',views.index,name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogenv/blog_project/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class blog(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post_author')
    blog_title=models.CharField(max_length=200, verbose_name='Put a Title')
    slug=models.SlugField(max_length=100,unique=True)
    blog_content=models.TextField(verbose_name='What is in your mind?')
    blog_image=models.ImageField(upload_to='blog_pics', verbose_name='image')
    publish_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=['-publish_date']

    def __str__(self):
        return self.blog_title
class comment(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    blog=models.ForeignKey(blog, on_delete=models.CASCADE, related_name='bolg_comment')
    comments=models.TextField(verbose_name='comment')
    comment_date=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-comment_date']

    def __str__(self):
        return self.comments
class like(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_like')
    blog=models.ForeignKey(blog, on_delete=models.CASCADE, related_name='blog_like')
    def __str__(self):
        return str(self.user) +" liked "+ str(self.blog)

blogenv/blog_project/blog_app/forms.py
from django import forms
from blog_app.models import *

class commentform(forms.ModelForm):
    comments = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'comment','placeholder':'Write Comment here..'}))
    class Meta:
        model = comment
        fields=['comments']

blogenv/blog_project/blog_app/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, ListView, View, DetailView, TemplateView, DeleteView
from blog_app.models import *
from blog_app.forms import *
import uuid

# Create your views here.
class myblogs(LoginRequiredMixin, TemplateView):
    model=blog
    template_name = 'blog_app/my_blog.html'

class editblog(LoginRequiredMixin,UpdateView):
    model = blog
    template_name = 'blog_app/edit_blog.html'
    fields = ['blog_title', 'blog_content', 'blog_image']
    def get_success_url(self, **kwargs):
        return reverse_lazy('blog_app:blog_details', kwargs={'slug':self.object.slug})


class createblog(LoginRequiredMixin, CreateView):
    model=blog
    template_name = 'blog_app/create_blog.html'
    fields = ['blog_title','blog_content','blog_image']


    def form_valid(self, form, ):
        blog_obj=form.save(commit=False)
        blog_obj.author=self.request.user
        title=blog_obj.blog_title
        blog_obj.slug=title.replace(" ", "-")+" "+str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class bloglist(ListView):
    context_object_name = 'blogs'
    model = blog
    template_name = 'blog_app/blog_list.html'

@login_required
def blog_details(request, slug):
    diction={}
    blogs=blog.objects.get(slug=slug)
    form=commentform()
    users=request.user
    already_liked = like.objects.filter(user=users, blog=blogs)

    if already_liked:
        liked=True
    else:
        liked=False

    diction.update({'liked':liked})

    if request.method=='POST':
        form=commentform(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.user=request.user
            comment.blog=blogs
            comment.save()
            return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug':slug}))
    diction.update({'blog':blogs})
    diction.update({'form':form})
    return render(request, 'blog_app/blog_details.html', context=diction)

@login_required
def liked(request, pk):
    blogs = blog.objects.get(pk=pk)
    user = request.user
    alredy_liked = like.objects.filter(user=user, blog=blogs)
    if not alredy_liked:
        like_post = like(user=user, blog=blogs)
        like_post.save()
    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug':blogs.slug}))

@login_required
def disliked(request, pk):
    blogs = blog.objects.get(pk=pk)
    users = request.user
    alredy_liked = like.objects.filter(user=users, blog=blogs)
    alredy_liked.delete()
    return HttpResponseRedirect(reverse('blog_app:blog_details', kwargs={'slug':blogs.slug}))

blogenv/blog_project/templates/blog_app/blog_details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{blog.blog_title}}{% endblock %}
{% block content %}
<h3>{{blog.blog_title}}</h3>
<h6>Publish date:&nbsp;{{blog.publish_date}}</h6>
<h6>Update date:&nbsp;{{blog.update_date}}</h6>
<h6>Author:&nbsp;@{{blog.author}}</h6>
<hr>
<div class="row">
<div class="col-sm-8">
<img src="/media/{{blog.blog_image}}" height="500px" width="730px">
</div>
<div style="margin-left:15px;">
<p>{{blog.blog_content|linebreaks}}</p>
<hr>

<div>
    <h5>Likes:{{blog.blog_like.count}}</h5>
    {% if not liked %}
    <a href="{% url 'blog_app:like' pk=blog.pk %}"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></a>
    {% else %}
    <a href="{% url 'blog_app:dislike' pk=blog.pk %}"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i></a>
    {% endif %}
</div>



</div>
</div><br>
<h6>Comment Section:</h6>
<form method="POST">
    <hr>
    {{form}}<br>
    {% csrf_token %}
    <button type="submit" style="position: relative; margin-left: 672px;" class="btn btn-info btn-sm">Send</button>
    <hr>
</form>

<div>
    <h5>Comments:&nbsp;{{blog.bolg_comment.count}}</h5>
    {% for comment in blog.bolg_comment.all %}
    <p>@{{comment.user}}&ensp;{{comment.comment_date}}<br>
    {{comment.comments}}</p>

    {% endfor %}
</div>
{% endblock %}

blogenv/blog_project/templates/blog_app/blog_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load custom_filters %}
<title>blog list</title>
{% block content %}
{% for blog in blogs %}
<h4>{{blog.blog_title}}</h4>
{{blog.publish_date}}<br>
<div class="row">
<div class="col-sm-4">
<img src="/media/{{blog.blog_image}}" height="150px" width="200">
</div>
<div class="col-sm-8">
<p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'blog_app:blog_details' slug=blog.slug %}">Continue reading..</a></p>
<p>{{blog.bolg_comment.count}}&nbsp;Comments&ensp;&ensp;&ensp;{{blog.blog_like.count}}&nbsp;Likes</p>
<a href="#" style="color:black;">@{{blog.author}}</a>
</div>
</div>
<hr>
{% endfor %}

{% endblock %}

blogenv/blog_project/templates/blog_app/create_blog.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create Blog{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    <h4>Write your blog here:</h4>
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Post</button>
</form>
{% endblock %}

blogenv/blog_project/templates/blog_app/edit_blog.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{blog.blog_title}}{% endblock %}
{% block content %}
{% if blog.author == user %}
<form method="POST" enctype="multipart/form-data">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Update</button>
{% else %}
<div class="alert alert-danger">
    <h4>Not allowed to update blog!!!</h4>
</div>
{% endif %}
</form>
{% endblock %}

blogenv/blog_project/templates/blog_app/my_blog.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} {{user}} {% endblock %}
{% block content %}
{% for blog in user.post_author.all %}
<h4>{{blog.blog_title}}</h4>
{{blog.publish_date}}<br>
<div class="row">
<div class="col-sm-4">
<img src="/media/{{blog.blog_image}}" height="150px" width="200">
</div>
<div class="col-sm-8">
<p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'blog_app:blog_details' slug=blog.slug %}">Continue reading..</a>
<a href="{% url 'blog_app:editblog' pk=blog.pk %}" style="color:green; margin-left:20px;"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Edit Blog</a>
</p>
<a href="#" style="color:black;">@{{blog.author}}</a>
</div>
</div>
<hr>
{% endfor %}

{% endblock %}